from yacs.config import CfgNode as CN

__C=CN()
cfg=__C

__C.DEVICE='0'

__C.VISIABLE=CN()
__C.VISIABLE.ORIGINAL='./visiable/original_plot'
__C.VISIABLE.PC='./visiable/pc_plot'
__C.VISIABLE.MTIMTD='./visiable/mtimtd_plot'
__C.VISIABLE.PCTEST='./visiable/pc_test'
__C.VISIABLE.TOTAL_PC='./visiable/pc_total'
__C.VISIABLE.MTIMTDSUM='./visiable/mtimtd_sum_plot'

__C.DATA=CN()
__C.DATA.GEN_DATA_DICT='./LN_data/Gen_data'
__C.DATA.GEN_G_TRAIN_DATA='./G_data/train'
__C.DATA.GEN_G_TEST_DATA='./G_data/test'
__C.DATA.GEN_S_TRAIN_DATA='./S_data/train'
__C.DATA.GEN_S_TEST_DATA='./S_data/test'
__C.DATA.GEN_SIM_S_TRAIN_DATA='/media/user/12189ab3-1343-9543-9b73-946b1a0b74f2/SEN/RAVA_CL/train'
__C.DATA.GEN_SIM_S_TEST_DATA='./Sim_S_data/test'
__C.DATA.N_CHANNELS=1
__C.DATA.N_CLASSES=2
__C.DATA.ORI_DATA_DICT='/data/sen/ln_ori_data/track_in_data'
__C.DATA.CHECK_MAT='/data/sen/ln_ori_data/Check_new.mat'
__C.DATA.ORI_NONE_DATA_DICT='/data/sen/ln_ori_data/none_data'
__C.DATA.TRAIN_SIZE=10000

__C.CA_CFAR=CN()
__C.CA_CFAR.NREF=8
__C.CA_CFAR.NPRO=8
__C.CA_CFAR.CUT=1
__C.CA_CFAR.PFA=3e-2

__C.SIMULATION=CN()
__C.SIMULATION.VMIN=100
__C.SIMULATION.VMAX=300
__C.SIMULATION.SNR_MIN=10
__C.SIMULATION.SNR_MAX=15
__C.SIMULATION.LEN_7=6096
__C.SIMULATION.NUMMAX=3
# __C.SIMULATION.WIN_SIZE=7
__C.SIMULATION.WIN_SIZE=3

__C.GAUSSIAN=CN()
__C.GAUSSIAN.TRAIN_TARGET_SIZE=50000
__C.GAUSSIAN.TRAIN_CLUTTER_SIZE=80000
__C.GAUSSIAN.TEST_TARGET_SIZE=10000
__C.GAUSSIAN.SNR_MIN=10
__C.GAUSSIAN.SNR_MAX=12
__C.GAUSSIAN.LEN=4096
__C.GAUSSIAN.SPLIT_LEN=512
__C.GAUSSIAN.NUMMAX=3
__C.GAUSSIAN.WIN_SIZE=1
__C.GAUSSIAN.SMALL_LEN=128
__C.GAUSSIAN.SMALL=True
__C.GAUSSIAN.TRAIN=True
__C.GAUSSIAN.TRANSFORM_NOISE=0.1 #
__C.GAUSSIAN.FEATURE_DIM=128
__C.GAUSSIAN.TEMPERATURE=0.2

__C.SEA_CLUTTER=CN()
__C.SEA_CLUTTER.DICT='./S_data'
__C.SEA_SIMULATION=CN()


# ---------10 12 128 args-----------
# __C.SEA_SIMULATION.TRIAN_ECHOS=6000
# __C.SEA_SIMULATION.SNR_MIN=10
# __C.SEA_SIMULATION.SNR_MAX=12
# __C.SEA_SIMULATION.FEATURE_DIM=128
# __C.SEA_SIMULATION.SMALL_LEN=128
# __C.SEA_SIMULATION.SMALL=True
# __C.SEA_SIMULATION.TRAIN=True
# __C.SEA_SIMULATION.LEN=4096
# __C.SEA_SIMULATION.NUMMAX=16
# __C.SEA_SIMULATION.WIN_SIZE=1
# __C.SEA_SIMULATION.TEMPERATURE=0.4
# __C.SEA_SIMULATION.V=2
# __C.SEA_SIMULATION.C=0.5
# ---------10 12 128 args-----------

# ---------10 12 128 args-----------
__C.SEA_CLUTTER.SNR_MIN=10
__C.SEA_CLUTTER.SNR_MAX=12
__C.SEA_CLUTTER.FEATURE_DIM=2048
__C.SEA_CLUTTER.SMALL_LEN=128
__C.SEA_CLUTTER.SMALL=True
__C.SEA_CLUTTER.TRAIN=True
__C.SEA_CLUTTER.LEN=5248
__C.SEA_CLUTTER.NUMMAX=5
__C.SEA_CLUTTER.WIN_SIZE=1
__C.SEA_CLUTTER.TEMPERATURE=0.4
# ---------10 12 128 args-----------

# ---------4 6 64 args-----------
# __C.SEA_SIMULATION.TRIAN_ECHOS=6000
# __C.SEA_SIMULATION.SNR_MIN=4
# __C.SEA_SIMULATION.SNR_MAX=6
# __C.SEA_SIMULATION.FEATURE_DIM=64
# __C.SEA_SIMULATION.SMALL_LEN=64
# __C.SEA_SIMULATION.SMALL=True
# __C.SEA_SIMULATION.TRAIN=True
# __C.SEA_SIMULATION.LEN=4096
# __C.SEA_SIMULATION.NUMMAX=32
# __C.SEA_SIMULATION.WIN_SIZE=1
# __C.SEA_SIMULATION.TEMPERATURE=0.4
# __C.SEA_SIMULATION.V=2
# __C.SEA_SIMULATION.C=0.5
# ---------4 6 64 args-----------

# ---------4 6 64 args-----------
# __C.SEA_CLUTTER.SNR_MIN=4
# __C.SEA_CLUTTER.SNR_MAX=6
# __C.SEA_CLUTTER.FEATURE_DIM=2048
# __C.SEA_CLUTTER.SMALL_LEN=64
# __C.SEA_CLUTTER.SMALL=True
# __C.SEA_CLUTTER.TRAIN=True
# __C.SEA_CLUTTER.LEN=3840
# __C.SEA_CLUTTER.NUMMAX=5
# __C.SEA_CLUTTER.WIN_SIZE=1
# __C.SEA_CLUTTER.TEMPERATURE=0.4
# ---------4 6 64 args-----------

# ---------1 3 64 args-----------
# __C.SEA_CLUTTER.SNR_MIN=1
# __C.SEA_CLUTTER.SNR_MAX=3
# __C.SEA_CLUTTER.FEATURE_DIM=64
# __C.SEA_CLUTTER.SMALL_LEN=64
# __C.SEA_CLUTTER.SMALL=True
# __C.SEA_CLUTTER.TRAIN=True
# __C.SEA_CLUTTER.LEN=4096
# __C.SEA_CLUTTER.NUMMAX=32
# __C.SEA_CLUTTER.WIN_SIZE=1
# __C.SEA_CLUTTER.TEMPERATURE=0.4
# ---------1 3 64 args-----------

# ---------7 9 64 args-----------
# __C.SEA_SIMULATION.TRIAN_ECHOS=6000
# __C.SEA_SIMULATION.SNR_MIN=7
# __C.SEA_SIMULATION.SNR_MAX=9
# __C.SEA_SIMULATION.FEATURE_DIM=64
# __C.SEA_SIMULATION.SMALL_LEN=64
# __C.SEA_SIMULATION.SMALL=True
# __C.SEA_SIMULATION.TRAIN=True
# __C.SEA_SIMULATION.LEN=4096
# __C.SEA_SIMULATION.NUMMAX=7
# __C.SEA_SIMULATION.WIN_SIZE=1
# __C.SEA_SIMULATION.TEMPERATURE=0.4
# __C.SEA_SIMULATION.V=2
# __C.SEA_SIMULATION.C=0.5
# ---------7 9 64 args-----------

# ---------7 9 64 args-----------
# __C.SEA_CLUTTER.SNR_MIN=7
# __C.SEA_CLUTTER.SNR_MAX=9
# __C.SEA_CLUTTER.FEATURE_DIM=2048
# __C.SEA_CLUTTER.SMALL_LEN=64
# __C.SEA_CLUTTER.SMALL=True
# __C.SEA_CLUTTER.TRAIN=True
# __C.SEA_CLUTTER.LEN=3840
# __C.SEA_CLUTTER.NUMMAX=5
# __C.SEA_CLUTTER.WIN_SIZE=1
# __C.SEA_CLUTTER.TEMPERATURE=0.1
# ---------7 9 64 args-----------

# ---------10 12 64 args-----------
__C.SEA_SIMULATION.TRIAN_ECHOS=6000
__C.SEA_SIMULATION.SNR_MIN=10
__C.SEA_SIMULATION.SNR_MAX=12
__C.SEA_SIMULATION.FEATURE_DIM=64
__C.SEA_SIMULATION.SMALL_LEN=64
__C.SEA_SIMULATION.SMALL=True
__C.SEA_SIMULATION.TRAIN=True
__C.SEA_SIMULATION.LEN=4096
__C.SEA_SIMULATION.NUMMAX=7
__C.SEA_SIMULATION.WIN_SIZE=1
__C.SEA_SIMULATION.TEMPERATURE=0.4
__C.SEA_SIMULATION.V=2
__C.SEA_SIMULATION.C=0.5
__C.SEA_SIMULATION.CROP_LEN=58 #90% 38 42 45 48 51 54 58 61
__C.SEA_SIMULATION.CROP_TEST=False
__C.SEA_SIMULATION.NOISE_TEST=True
__C.GAUSSIAN.TRANSFORM_NOISE=0.1 #
# ---------10 12 64 args-----------

# ---------10 12 64 args-----------
# __C.SEA_CLUTTER.SNR_MIN=10
# __C.SEA_CLUTTER.SNR_MAX=12
# __C.SEA_CLUTTER.FEATURE_DIM=2048
# __C.SEA_CLUTTER.SMALL_LEN=64
# __C.SEA_CLUTTER.SMALL=True
# __C.SEA_CLUTTER.TRAIN=True
# __C.SEA_CLUTTER.LEN=5248
# # __C.SEA_CLUTTER.LEN=3840
# __C.SEA_CLUTTER.NUMMAX=5
# __C.SEA_CLUTTER.WIN_SIZE=1
# __C.SEA_CLUTTER.TEMPERATURE=0.1
# ---------10 12 64 args-----------


# ---------10 12 32 args-----------
# __C.SEA_SIMULATION.TRIAN_ECHOS=6000
# __C.SEA_SIMULATION.SNR_MIN=10
# __C.SEA_SIMULATION.SNR_MAX=12
# __C.SEA_SIMULATION.FEATURE_DIM=32
# __C.SEA_SIMULATION.SMALL_LEN=32
# __C.SEA_SIMULATION.SMALL=True
# __C.SEA_SIMULATION.TRAIN=True
# __C.SEA_SIMULATION.LEN=4096
# __C.SEA_SIMULATION.NUMMAX=64
# __C.SEA_SIMULATION.WIN_SIZE=1
# __C.SEA_SIMULATION.TEMPERATURE=0.4
# __C.SEA_SIMULATION.V=2
# __C.SEA_SIMULATION.C=0.5
# ---------10 12 32 args-----------

# ---------10 12 32 args-----------
# __C.SEA_CLUTTER.SNR_MIN=10
# __C.SEA_CLUTTER.SNR_MAX=12
# __C.SEA_CLUTTER.FEATURE_DIM=2048
# __C.SEA_CLUTTER.SMALL_LEN=32
# __C.SEA_CLUTTER.SMALL=True
# __C.SEA_CLUTTER.TRAIN=True
# __C.SEA_CLUTTER.LEN=5248
# __C.SEA_CLUTTER.NUMMAX=5
# __C.SEA_CLUTTER.WIN_SIZE=1
# __C.SEA_CLUTTER.TEMPERATURE=0.4
# ---------10 12 32 args-----------

# ---------10 12 16 args-----------
# __C.SEA_SIMULATION.TRIAN_ECHOS=6000
# __C.SEA_SIMULATION.SNR_MIN=10
# __C.SEA_SIMULATION.SNR_MAX=12
# __C.SEA_SIMULATION.FEATURE_DIM=16
# __C.SEA_SIMULATION.SMALL_LEN=16
# __C.SEA_SIMULATION.SMALL=True
# __C.SEA_SIMULATION.TRAIN=True
# __C.SEA_SIMULATION.LEN=4096
# __C.SEA_SIMULATION.NUMMAX=128
# __C.SEA_SIMULATION.WIN_SIZE=1
# __C.SEA_SIMULATION.TEMPERATURE=0.4
# __C.SEA_SIMULATION.V=2
# __C.SEA_SIMULATION.C=0.5
# ---------10 12 16 args-----------

# ---------10 12 16 args-----------
# __C.SEA_CLUTTER.SNR_MIN=10
# __C.SEA_CLUTTER.SNR_MAX=12
# __C.SEA_CLUTTER.FEATURE_DIM=2048
# __C.SEA_CLUTTER.SMALL_LEN=16
# __C.SEA_CLUTTER.SMALL=True
# __C.SEA_CLUTTER.TRAIN=True
# __C.SEA_CLUTTER.LEN=5248
# __C.SEA_CLUTTER.NUMMAX=5
# __C.SEA_CLUTTER.WIN_SIZE=1
# __C.SEA_CLUTTER.TEMPERATURE=0.4
# ---------10 12 16 args-----------

# ---------10 12 8 args-----------
# __C.SEA_CLUTTER.SNR_MIN=10
# __C.SEA_CLUTTER.SNR_MAX=12
# __C.SEA_CLUTTER.FEATURE_DIM=8
# __C.SEA_CLUTTER.SMALL_LEN=8
# __C.SEA_CLUTTER.SMALL=True
# __C.SEA_CLUTTER.TRAIN=True
# __C.SEA_CLUTTER.LEN=4096
# __C.SEA_CLUTTER.NUMMAX=256
# __C.SEA_CLUTTER.WIN_SIZE=1
# __C.SEA_CLUTTER.TEMPERATURE=0.4
# ---------10 12 8 args-----------

__C.TRAIN=CN()
__C.TRAIN.BATCH_SIZE=512
__C.TRAIN.WEIGHT_DECAY=0.0001
__C.TRAIN.LR=1e-4
__C.TRAIN.EPOCH=50
__C.TRAIN.TRAINED_PARAMETER_PATH='./result/trained_parameters'
__C.TRAIN.TRAIN_SIM_SEA_CLUTTER=True
__C.TRAIN.LABELED_SAMPLES=160
__C.TRAIN.LINEAR=False

__C.TEST=CN()
__C.TEST.BATCH_SIZE=16
__C.TEST.TEST_BATCH_SIZE=512
__C.TEST.SIM_TEST_LOG_DIR='./result/sim_test_log'
__C.TEST.TEST_LOG_DIR='./result/conf_test_log'
__C.TEST.TEST_STABLE_LOG_DIR='./result/stable_test_log'
